### ISSUE TITLE
Add Products Dropdown to Navbar

### ISSUE THREAD

**Issue by ankushbhardwaj408** [layer5io/docs#108]
#### Desired Behavior
Improve navbar with a user-friendly product dropdown menu in the navbar that showcases our products.

#### Screenshots
![Screenshot 2023-12-06 213151](https://github.com/layer5io/docs/assets/93874580/ee641101-a0fa-4111-a7eb-a8e159294f9e)

#### Mockups

---
**[Contributor Guide](https://docs.meshery.io/project/contributing)**
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)

**Comment by ankushbhardwaj408** [comment]
@leecalcote I would like to work on that.

**Comment by Raj100679** [comment]
@leecalcote , Can I know what has to be done here, I would love to work on this?

**Comment by Akshun-01** [comment]
Hey @leecalcote, I would like to work on this one, if it's free.

**Comment by ankushbhardwaj408** [comment]
Hi @akshun-01 I did not take reference from the code. I used the mockup from #82.

**Comment by Akshun-01** [comment]
Hey @ritiksaxena124, I am almost done with the dropdown component. Actually, I was just about to add breakpoints for responsiveness, but when I was doing that I realized that the homepage is not responsive for starters (I checked the deployed site and on my mobile as well.) 
![image](https://github.com/layer5io/docs/assets/93793691/facbae82-a88c-41ea-b020-8096ef709195)

I think we should first make the base responsive so that other elements are not that tough to configure.

**Comment by Akshun-01** [comment]
https://github.com/layer5io/docs/assets/93793691/58bbe075-13c8-4133-b8ae-1b2c75a47f58

Also, this is the current state of the dropdown, I will be adding responsive breakpoints later.
And if you want anything to be changed or tweaked, please give your feedback. So that I may work on it!

**Comment by iArchitSharma** [comment]
Just for reference, this issue is now being addressed here: https://github.com/layer5io/docs/issues/127
Therefor am closing this issue!
