### ISSUE TITLE
[Docs] Kanvas release notes pages missing notes 

### ISSUE THREAD

**Issue by leecalcote** [layer5io/docs#385]
#### Current State
Click on any of the releases and see that there are no details captured - https://docs.layer5.io/kanvas/reference/releases/

#### Desired State
Details of the changelog (a copy of release drafter) for each release made.

---

#### Contributor Guide and Resources
- 📚 [Instructions for contributing to documentation](https://github.com/layer5io/docs/blob/master/CONTRIBUTING.md)
   - Layer5 documentation [site](https://docs.layer5.io) and [source](https://github.com/layer5io/docs/)
- 🎨 Wireframes and [designs for Layer5 site](https://www.figma.com/file/5ZwEkSJwUPitURD59YHMEN/Layer5-Designs) in Figma [(open invite)](https://www.figma.com/team_invite/redeem/qJy1c95qirjgWQODApilR9)
- 🙋🏾🙋🏼 Questions: [Layer5 Discussion Forum](https://discuss.layer5.io) and [Layer5 Community Slack](http://slack.layer5.io)

**Comment by jerensl** [comment]
This issues related to versioning Meshery Extensions, Release drafter have not generated the version of Meshery extensions because their don't understand to make release notes outside of semantic versioning which cascade to this workflow.

Simply speaking there are no changelog generated for each version in meshery-extension.

**Comment by leecalcote** [comment]
Release note details are now included. Thank you, @jerensl 👍
